version: '2'

volumes:
  postgres_data: {}
  postgres_backup: {}
  caddy: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
      args:
        SETUPTOOLS_VERSION: 75.8.0
        PIP_VERSION: 25.3
        PIP_TOOLS_VERSION: 7.5.2
    depends_on:
      - postgres
      - redis
    env_file: .env
    command: /gunicorn.sh

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_backup:/backups
    env_file: .env

  caddy:
    build:
      context: .
      dockerfile: ./compose/production/caddy/Dockerfile
    depends_on:
      - django
    volumes:
      - caddy:/root/.caddy
    env_file: .env
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"

  redis:
    image: redis:7-alpine

  # celeryworker:
  #   <<: *django
  #   depends_on:
  #    - postgres
  #    - redis
  #   command: /start-celeryworker.sh

  # celerybeat:
  #   <<: *django
  #   depends_on:
  #     - postgres
  #     - redis
  #   command: /start-celerybeat.sh
