version: '2'

volumes:
  postgres_data_local: {}
  postgres_backup_local: {}


services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
      args:
        SETUPTOOLS_VERSION: 75.8.0
        PIP_VERSION: 25.3
        PIP_TOOLS_VERSION: 7.5.2
    depends_on:
      - postgres
      - mailhog
    volumes:
      - .:/app
    env_file: .env
    ports:
      - "8343:8343"
    command: /start.sh
    stdin_open: true
    tty: true

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    volumes:
      - postgres_data_local:/var/lib/postgresql/data
      - postgres_backup_local:/backups
    env_file: .env
  mailhog:
    image: mailhog/mailhog:v1.0.0
    ports:
      - "8025:8025"


  redis:
    image: redis:7-alpine

  # celeryworker:
  #   <<: *django
  #   depends_on:
  #     - redis
  #     - postgres
  #     - mailhog
  #   ports: []
  #   command: /start-celeryworker.sh

  # celerybeat:
  #   <<: *django
  #   depends_on:
  #     - redis
  #     - postgres
  #     - mailhog
  #   ports: []
  #   command: /start-celerybeat.sh
